### ISSUE TITLE
Upgrade to python 3.12 upsteam breaks pip install of deltalake for the jupyter container

### ISSUE THREAD

**Issue by markemberson** [rylativity/container-analytics-platform#5]
178.8   note: This error originates from a subprocess, and is likely not a problem with pip.
178.8   ERROR: Failed building wheel for pyarrow
178.8 Successfully built pyspark psycopg2
178.8 Failed to build pyarrow
178.8 ERROR: Could not build wheels for pyarrow, which is required to install pyproject.toml-based projects
------
failed to solve: process "/bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 1

**Comment by rylativity** [comment]
Resolved in https://github.com/rylativity/container-analytics-platform/pull/6.

Closing.
